# -*- coding: utf-8 -*-
"""Autofix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZzIS6aLHf9oH6cxNrA5DZz46o0h6y8d

# Phase 2

## Remove Old PackShot
"""

def remove_old_packshot(img_pil, pack):
    if pack is None:
        return img_pil

    x, y, w, h = pack
    img = img_pil.copy()
    draw = ImageDraw.Draw(img)
    bg = img.getpixel((10, 10))
    draw.rectangle([x, y, x+w, y+h], fill=bg)
    return img

"""## Safe Zone Fix"""

def fix_safe_zones(img_pil, boxes, rules):
    safe = rules["rules"]["safe_zones"]
    top_safe = safe["top"]
    bottom_safe = safe["bottom"]

    fixed = img_pil.copy()
    draw = ImageDraw.Draw(fixed)
    W, H = fixed.size
    bg = fixed.getpixel((10, 10))

    updated = []
    for b in boxes:
        x, y, w, h = b["bbox"]
        orig_y = y

        if y < top_safe:
            y = top_safe
        if y + h > H - bottom_safe:
            y = H - bottom_safe - h

        if y != orig_y:
            draw.rectangle([x, orig_y, x+w, orig_y+h], fill=bg)
            draw.text((x, y), b["text"], fill="white")

        b["bbox"] = [x, y, w, h]
        updated.append(b)

    return fixed, updated

"""## Center Text"""

def center_text_elements(img_pil, boxes):
    fixed = img_pil.copy()
    draw = ImageDraw.Draw(fixed)
    W, H = fixed.size
    bg = fixed.getpixel((10, 10))

    # Pick largest text as headline
    if not boxes:
        return fixed

    headline = max(boxes, key=lambda b:b["bbox"][2] * b["bbox"][3])

    text = headline["text"]
    x, y, w, h = headline["bbox"]

    draw.rectangle([x, y, x+w, y+h], fill=bg)

    new_x = int((W - w) / 2)
    new_y = int(H * 0.10)

    draw.text((new_x, new_y), text, fill="white")
    headline["bbox"] = [new_x, new_y, w, h]

    return fixed

"""## RePaint PackShot"""

def fix_packshot(img_pil, rules):
    pack = detect_packshot(img_pil)
    if pack is None:
        return img_pil

    x, y, w, h = pack
    W, H = img_pil.size

    fixed = remove_old_packshot(img_pil, pack)
    draw = ImageDraw.Draw(fixed)

    # New size
    new_w = int(W * 0.28)
    new_h = int(H * 0.32)

    new_x = (W - new_w) // 2
    new_y = int(H * 0.55)

    # Draw placeholder box
    draw.rectangle([new_x, new_y, new_x+new_w, new_y+new_h],
                   outline="white", width=6)

    return fixed

"""## Master Pipeline"""

import re
from PIL import ImageDraw

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9 %]", "", text)
    return text.strip()


def clear_box(img, bbox, bg_color):
    draw = ImageDraw.Draw(img)
    x, y, w, h = bbox
    draw.rectangle([x, y, x + w, y + h], fill=bg_color)

def auto_fix_creative(img, boxes, rules):
    draw = ImageDraw.Draw(img)
    bg_color = img.getpixel((5, 5))  # green background

    safe_top = rules["rules"]["safe_zones"]["top"]

    current_y = safe_top + 20
    line_gap = 30

    for b in boxes:
        raw_text = b["text"]
        text = normalize_text(raw_text)

        # 🚫 Ignore OCR garbage
        if len(text) < 4:
            continue

        # 🚫 Ignore forbidden copy
        if any(f.upper() in text for f in rules["rules"]["forbidden_copy"]):
            continue

        # ✅ Clear old text
        clear_box(img, b["bbox"], bg_color)

        x, _, w, h = b["bbox"]

        # ✅ Controlled vertical stacking (NO overlap)
        draw.text((x, current_y), text, fill="white")
        current_y += h + line_gap

    return img