# -*- coding: utf-8 -*-
"""Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbRnB_Oha9wI8AKOpuNqfz_0SCGlca9g

# Phase 1

## OCR Function
"""

import pytesseract
from PIL import Image

def run_ocr(img):
    data = pytesseract.image_to_data(img, output_type=pytesseract.Output.DICT)

    boxes = []
    for i, text in enumerate(data["text"]):
        if text.strip():
            boxes.append({
                "text": text,
                "bbox": [
                    data["left"][i],
                    data["top"][i],
                    data["width"][i],
                    data["height"][i]
                ]
            })
    return boxes

"""## PackShot Detector"""

def detect_packshot(img_pil):
    img = img_pil.convert("RGB")
    W, H = img.size
    pix = img.load()

    found_pixels = []

    for y in range(H):
        for x in range(W):
            r, g, b = pix[x, y]

            # bright-ish object (packshot usually white/bright)
            if r > 180 and g > 180 and b > 180:
                found_pixels.append((x, y))

    if not found_pixels:
        return None

    xs = [p[0] for p in found_pixels]
    ys = [p[1] for p in found_pixels]

    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)

    w = max_x - min_x
    h = max_y - min_y

    return [min_x, min_y, w, h]

"""## Validation ONLY"""

def validate_creative(img, boxes, pack_bbox, rules):
    violations = []

    # Safe zone validation
    for b in boxes:
        x, y, w, h = b["bbox"]
        if y < rules["rules"]["safe_zones"]["top"]:
            violations.append({
                "type": "safe_zone",
                "text": b["text"],
                "issue": "top_safe_zone"
            })

    # Packshot validation
    if pack_bbox is None:
        violations.append({
            "type": "packshot",
            "issue": "missing"
        })

    return violations